name: 'local_bike'
version: '1.0.0'

profile: 'local_bike'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  local_bike:
    staging:
      +materialized: view
      +schema: stg_local_bike
    intermediate:
      +materialized: view
      +schema: int_local_bike
    mart:
      +materialized: table
      +schema: mart