version: 2

sources:
  - name: local_bike
    schema: public
    tables:
      - name: brands
      - name: categories
      - name : customers
      - name : orders
      - name : order_items
      - name : products
      - name : stocks
      - name : staffs
      - name : stores
